### ISSUE TITLE
Savings Calculation issues#2

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#16]
In all the excel files provided, the Savings Potential column (e.g. 20%), refers to which of the points below ?
-Savings of this specific feature ?
-Savings of this specific equipment/process efficiency score ?
-Savings of the Efficiency Score (of the scenario) ?
-Savings of the EMSA Score (of the scenario) ?

Could you please clarify on that because this information is not very clear.

**Comment by AaronITCL** [comment]
> In all the excel files provided, the Savings Potential column (e.g. 20%), refers to which of the points below ?
> -Savings of this specific feature ?
> -Savings of this specific equipment/process efficiency score ?
> -Savings of the Efficiency Score (of the scenario) ?
> -Savings of the EMSA Score (of the scenario) ?

Answering to your question, this affects to: Savings of this specific equipment/process and this later will affect the calculation of the new Efficiency Score and so the EMSA Score.

To clarify this:

The saving potential affects to the Energy consumption of the correspondant equipment or process,  acording to this new Energy consumption you have to recalculate the new Efficiency score, taking into account that this new value is not the real Efficiency score of the company, it is the score after the improvement actions, so that score must not replace the real score of the company and have not to be save into the benchmarking.

![image](https://user-images.githubusercontent.com/33861863/33420567-5c88f084-d5af-11e7-8e34-09c1b17c573e.png)

**Comment by WINGSTeam** [comment]
Thanks for the info. We just have a doubt:
According to the document: 
[EFFICIENCY_SCORE.docx](https://github.com/EnergyWater/EMSA/files/1517653/EFFICIENCY_SCORE.docx)
Efficiency Score is calculated for all Equipment and Processes (that a user has selected). As a result, we don't calculate separate Efficiency score for Pump1, for Pump2, for Boiler1, for Boiler2 etc. Because if we calculate separately for Pump1-2 etc. then the attribute of "Number of processes answered/ Total" would be always '0', because we are not answering any Processes if we are assessing Pump1-2 etc. separately.

Moreover, the function of the Efficiency Score does not include explicitly the attribute of energy consumption.

**Comment by AaronITCL** [comment]
The improvement of any of the features of any equipment or process will increment the Efficiency Score, beacause that improvement will transform that feature into a recommended value.
In the document attached this is referred to the 4th aspect: "Number of key factors in their recommended values/ Number of key factor features answered (40%)"

> Moreover, the function of the Efficiency Score does not include explicitly the attribute of energy consumption.

You are right, but the new Energy consumption has to be recalculated in order to show the new ratio if the user does the improvements

**Comment by WINGSTeam** [comment]
Could you clarify how the fuel savings are calculated because we are unable to find this information in the documents.

**Comment by AaronITCL** [comment]
Just to clarify.

In the indicators´ summary table it is vinculated each process and equipments to a type of energy consumed, for this consumption you have to apply the savings results of the improvements actions simulations.

The following image shows an example with the pump equipment, in this case the cunsumption is electricity, but working with fuel, the metodology is the same, but in this case the results appears in the fuel tab.

![image](https://user-images.githubusercontent.com/33861863/33552870-c666aaba-d8f6-11e7-80c6-309c4b55337f.png)

**Comment by WINGSTeam** [comment]
@AaronITCL One more thing regarding the indicators. There is a type called "Thermal exchange" , except the "Electrical" and "Fuel". Thermal is the same as "Fuel" so we do the savings as we do for the fuel ?

**Comment by SOCAMEX** [comment]
I think that's possible an industry  connected to a central heating and the energy is paid per Kcal consumed. This energy is consumed in the heating system and the savings will be the same

But this needs the ITCL validation

**Comment by WINGSTeam** [comment]
So, shall we consider 'Thermal Exchange' as 'Fuel'? Thanks

**Comment by AaronITCL** [comment]
Yes, and thanks @SOCAMEX for the explanation.
