### ISSUE TITLE
Recommendation and improvement actions

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#4]
According with the Socamex´s excels, the EMSA must display correctly the pertinant improvements and recommendatios, of the efficiency tab, based on the values set in the scenario´s module.

_You can find these documents updated in the EnergyWater Proyectplace´s project. (Documents -> WP2 -> Process-Equipments)_

**Comment by AaronITCL** [comment]
Dear @WINGSTeam nowadays, improvements and recommendations actions are displaying wrongly, maybe it is because it has been solved in an offline version?

**Comment by WINGSTeam** [comment]
Could you specify some of the improvements or recommendation that are not displayed correctly to have a better idea of the problem ?

**Comment by AaronITCL** [comment]
One example is on the boiler, as you can see, it is displaying all the recommendations and none improvements.

![captura](https://user-images.githubusercontent.com/33861863/33824957-58d176e6-de60-11e7-9291-faf2b9581117.PNG)

Pump is working wrongly too, but not as the boiler. 
I could divide it in 3 types of issues:
- An improvement or recommendation is not displaying when it should and vice versa
- Recommendations or improvements appear in the wrong column.
- EMSA displays improvements or recommendations when a user didn´t set any value in that feature.

**Comment by WINGSTeam** [comment]
> One example is on the boiler, as you can see, it is displaying all the recommendations and none improvements.

Boiler has been fixed!

**Comment by AaronITCL** [comment]
@WINGSTeam, by our side, we cannot see that, EMSA is still displaying all the recommendations and none improvements in the boiler´s equipment.

**Comment by WINGSTeam** [comment]
Have you submitted again the boiler and the efficiency part ? If not please do, else send us some more information regarding the account and the scenario name to check it internally.

**Comment by AaronITCL** [comment]
Yes, I have submitted the scenario several times and I´ve even recreate the scenario to check it.
Account: **emsacompanytest01**
Scenario: **GITHUB**

**Comment by WINGSTeam** [comment]
> @WINGSTeam, by our side, we cannot see that, EMSA is still displaying all the recommendations and none improvements in the boiler´s equipment.

> Yes, I have submitted the scenario several times and I´ve even recreate the scenario to check it.
> Account: emsacompanytest01
> Scenario: GITHUB

I have checked the specific scenario and i saw that you have not selected the correct values in order to display the improvements of the boiler. The features F45 kai F50 should be "No" from what we have seen from SOCAMEX excels' .
Here is a screenshot of the values of your scenario :
![screen shot 2017-12-12 at 14 51 49](https://user-images.githubusercontent.com/33901428/33885629-93302020-df4c-11e7-9d18-50ac4f417d5c.png)
And also a screenshot of the boiler displaying the two improvements of the Boiler:
![screen shot 2017-12-12 at 14 52 32](https://user-images.githubusercontent.com/33901428/33885675-b64f20a6-df4c-11e7-8d2c-585c6755b4d4.png)

**Comment by AaronITCL** [comment]
You are right, but the recommendations display still working wrongly
