### ISSUE TITLE
NEW ENERGY ANGELS CANNOT BE VIEWED ALTHOUGH THEY HAVE BEEN VALIDATED

### ISSUE THREAD

**Issue by SOCAMEX** [EnergyWater/EMSA#40]
We have validated an energy angel from the administrator's acount, but when we log in as a company we are not able to visualize the new energy angel among the options.

**Comment by SOCAMEX** [comment]
OK, we have already fixed it. From the administration account, you have to go to Energy Angels Information, select "view info" and then click on one to three services to provide (and accept services).

**Comment by david-ITCL** [comment]
Exactly, for an Energy Angel to appear on the list, s/he needs first to be accepted in the service they are interested in by the EMSA Adminsitrator. Besides, if you want to connect an Energy Angel with a company, only Service 1 is needed.
Now there is not a problem between people inside the consortium partners, but in the future, we need to be careful in this issue because a training certificate (from on-site training sessions or MOOC) would be required to accept Service 1
