### ISSUE TITLE
CORRECTION BY SOCAMEX (II) (PARTIAL)

### ISSUE THREAD

**Issue by SOCAMEX** [EnergyWater/EMSA#54]
To the moment, we have validated the modules "scenarios" and "results" of our processes. Here I attach an updated version of the mistakes detected, which is cumulative (it includes all the validation peformed so far, and thus includes the issues described in the first revision (tab "modulo escenarios"), plus new ones (tab "RESULTS module")). We are still working on it, and soon I will upload updated versions of the document.

[Process-Equipment follow-up 28FebSOCAMEX.xlsx](https://github.com/EnergyWater/EMSA/files/1767141/Process-Equipment.follow-up.28FebSOCAMEX.xlsx)

**Comment by WINGSTeam** [comment]
Everything is done, except that for the ratios.

It is true that the Production Ratios were wrongly expressed in (kwh/m3), but we think in (m3/kg) will be also wrong because production is measured in production units (by default). So what do you think? Is (m3/production) ok?

@david-ITCL , @AaronITCL , @SOCAMEX  what should we do on this ?
