### ISSUE TITLE
Simulation issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#79]
We have simulate some issues from an especific process, and EMSA displays the following:
![image](https://user-images.githubusercontent.com/33861863/38616494-7ea1ec78-3d94-11e8-8c4e-7f66530acd7d.png)
A negative improvement can´t be possible

**Comment by WINGSTeam** [comment]
This happens because the values you insert in the general questions section are lower than the values from your current scenario. For example, let’s say you have a scenario with the process pumping and equipment pump. In the Efficiency Questions section, the tool asks you the energy consumption for these process and equipment. Let’s say that your energy consumption for pumping is 2000kW and for pump is 1000kW. The total energy consumption for the current scenario is 3000kW. So, you cannot have a total energy consumption, in the general question section, that is lower than 3000kW, or a negative result will occur.
