### ISSUE TITLE
P29-30-31-32-33-34_Simulator_Saving

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#86]
[P29-30-31-32-33-34_Simulator_Saving_SMART FUTURE.xlsx](https://github.com/EnergyWater/EMSA/files/1988553/P29-30-31-32-33-34_Simulator_Saving_SMART.FUTURE.xlsx)

**Comment by WINGSTeam** [comment]
In your document, you mention that a lot of  fields and calculations have zero values. All the calculations seems to work fine for us, so we cannot replicate these problems. First of all, make sure you complete all the answers in the data evaluation module (general, efficiency, management), so all the necessary values are calculated and also make sure you submitted your scenario. If you continue to have the same problem, please send us your account credentials in order to check it as well. Also, we attach your excel file with our comments, below.

[P29-30-31-32-33-34_Simulator_Saving_SMART.FUTURE- WINGS-Response.xlsx](https://github.com/EnergyWater/EMSA/files/2005333/P29-30-31-32-33-34_Simulator_Saving_SMART.FUTURE-.WINGS-Response.xlsx)

**Comment by Matilde-SmartFuture** [comment]
I checked what you mentioned and made comments in response, as you can see on attached file. Almost everything is fine now.
[P29-30-31-32-33-34_Simulator_Saving_SMART.FUTURE-.WINGS-Response-SF comments.xlsx](https://github.com/EnergyWater/EMSA/files/2009890/P29-30-31-32-33-34_Simulator_Saving_SMART.FUTURE-.WINGS-Response-SF.comments.xlsx)

**Comment by WINGSTeam** [comment]
You are right about the payback formula. We changed the calculation with the correct one.
