### ISSUE TITLE
CTC/CIT EMSA processes

### ISSUE THREAD

**Issue by CTC-CIT** [EnergyWater/EMSA#91]
Please see attached file for the EMSA evaluation, for the processes assigned to CTC.
[Summary of processes evaluation- CTC.xlsx](https://github.com/EnergyWater/EMSA/files/2016323/Summary.of.processes.evaluation-.CTC.xlsx)

**Comment by WINGSTeam** [comment]
First, about the “Submission without the unit problem” that you mention, it’ s not valid that the user can submit without insert the unit value. If the user doesn’t insert the unit in a question, the default unit is selected by the tool, which is always the first choice from the dropdown list.

Most of your other comments are about the questions meaning. As you know, the questions are provided to us by SOCAMEX, so we cannot really answer about their content. You need to consult SOCAMEX about the meaning of the questions, you are referring to in your evaluation file. These kind of questions (about energy consumption, flowrate, pumped water etc.) are repeated in the majority of processes and equipment, so if we changed them for these six processes you propose, we will need to change them for all the other processes and equipment as well. In order to do so, we need the agreement from all the partners on that. Thus, please ask the other partners about that and provide us with the final text for the questions we need to change.

The numbering of the questions is just for testing purposes and in the final version it will be hidden.
